import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import CurrentUser from "~/features/auth/components/current-user"

import "~/shared/styles/globals.css"
import { cn } from "~/shared/utils/cn"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", geistSans.variable, geistMono.variable)}>
        <div className="flex flex-col min-h-screen max-w-4xl mx-auto p-4">
          <header className="flex items-center justify-end">
            <CurrentUser />
          </header>
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  )
}
